// react/src/component/admin/EditCategory.jsx
import React, { useState, useEffect } from "react";
import ApiService from "../../service/ApiService";
import { useNavigate, useParams } from "react-router-dom";
import '../../style/addCategory.css'

const EditCategory = () => {
    const { categoryId } = useParams();
    const [name, setName] = useState('')
    const [message, setMessage] = useState('');
    const navigate = useNavigate();


    useEffect(() => {
        fetchCategory(categoryId);
    }, [categoryId])

    const fetchCategory = async () => {
        try {
            const response = await ApiService.getCategoryById(categoryId);
            setName(response.category.name);

        } catch (error) {
            setMessage(error.response?.data?.message || error.message || "Failed to get a category by id")
            setTimeout(() => {
                setMessage('');
            }, 3000)
        }
    }

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            const response = await ApiService.updateCategory(categoryId, { name });
            if (response.status === 200) {
                setMessage(response.message);
                setTimeout(() => {
                    setMessage('');
                    navigate("/admin/categories")
                }, 3000)
            }
        } catch (error) {
            setMessage(error.response?.data?.message || error.message || "Failed to save a category")
        }
    }

    return (
        <div className="add-category-page">
            {message && <p className="message">{message}</p>}
            <form onSubmit={handleSubmit} className="category-form">
                <h2>Edit Category</h2>
                <input type="text"
                    placeholder="Category Name"
                    value={name}
                    onChange={(e) => setName(e.target.value)} />

                <button type="submit">Update</button>
            </form>
        </div>
    )

}

export default EditCategory;

// angular/src/app/admin/editcategory/editcategory.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ApiService } from '../../service/api.service';
import { ActivatedRoute, Router } from '@angular/router';
@Component({
  selector: 'app-editcategory',
  standalone: true,
  imports: [ReactiveFormsModule, CommonModule],
  templateUrl: './editcategory.component.html',
  styleUrl: './editcategory.component.css'
})

export class EditcategoryComponent implements OnInit {
  categoryForm: FormGroup;
  message: any = null;
  categoryId: string = ''

  constructor(private apiService: ApiService, private router: Router, private fb: FormBuilder, private route: ActivatedRoute) {

    this.categoryForm = this.fb.group({
      name: ['', Validators.required]
    })
  }

  ngOnInit(): void {
    this.categoryId = this.route.snapshot.paramMap.get("categoryId") || '';
    this.fetchCategoryById();
  }

  fetchCategoryById(): void {

    if (this.categoryId) {
      this.apiService.getCategoryById(this.categoryId).subscribe({
        next: (response) => {
          this.categoryForm.patchValue({ name: response.category.name })
        },
        error: (error) => {
          console.log((error))
          this.message = error?.error?.message || "unable to get categoty by id";
          setTimeout(() => {
            this.message = null;
          }, 3000)
        }
      })
    }
  }



  handleSubmit(): void {
    if (this.categoryForm.valid) {
      this.apiService.updateCategory(this.categoryId, this.categoryForm.value).subscribe({
        next: (response) => {
          if (response.status === 200) {
            this.message = "Category successfully Updated"
            setTimeout(() => {
              this.message = null;
              this.router.navigate(['/admin/categories']);
            }, 3000)
          }
        },
        error: (error) => {
          console.log(error)
          this.message = error?.error?.message || "unable to update Category";
        }
      })
    }
  }

}

<div>
    <p *ngIf="message">{{message}}</p>

    <form [formGroup]="categoryForm" (ngSubmit)="handleSubmit()">
        <h2>Update Category</h2>

        <input type="text" placeholder="Category name" formControlName="name" 
        [class.invalid]="categoryForm.get('name')?.invalid && categoryForm.get('name')?.touched">

        <button type="submit" [disabled]="categoryForm.invalid"> Update Category</button>
    </form>
</div>
