// frontend/src/app/admin/addcategory/addcategory.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ApiService } from '../../service/api.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-addcategory',
  standalone: true,
  imports: [ReactiveFormsModule, CommonModule],
  templateUrl: './addcategory.component.html',
  styleUrl: './addcategory.component.css'
})
export class AddcategoryComponent {
  categoryForm: FormGroup;
  message: any = null;

  constructor(private apiService:ApiService, private router:Router, private fb:FormBuilder){

    this.categoryForm = this.fb.group({
      name: ['', Validators.required]
    })
  }

  handleSubmit():void{
    if(this.categoryForm.valid){
      this.apiService.createCategory(this.categoryForm.value).subscribe({
        next:(response) =>{
          if (response.status === 200) {
            this.message = "categoty successfully saved"
            setTimeout(()=>{
              this.message = null;
              this.router.navigate(['/admin/categories']);
            }, 3000)
          }
        },
        error:(error) => {
          console.log(error)
          this.message = error?.error?.message || "unable to save category";
        }
      })
    }
  }

}

// react/src/component/admin/AddCategory.jsx
import React, { useState } from "react";
import ApiService from "../../service/ApiService";
import { useNavigate } from "react-router-dom";
import '../../style/addCategory.css'

const AddCategory = () => {
    const [name, setName] = useState('');
    const [message, setMessage] = useState('');
    const navigate = useNavigate();

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            const response = await ApiService.createCategory({name});
            if (response.status === 200) {
                setMessage(response.message);
                setTimeout(()=>{
                    setMessage('');
                    navigate("/admin/categories")
                }, 3000)
            }
        } catch (error) {
            setMessage(error.response?.data?.message || error.message || "Failed to save a category")
        }
    }

    return(
        <div className="add-category-page">
            {message && <p className="message">{message}</p>}
            <form onSubmit={handleSubmit} className="category-form">
                <h2>Add Category</h2>
                <input type="text"
                placeholder="Category Name"
                value={name}
                onChange={(e)=> setName(e.target.value)} />

                <button type="submit">Add</button>
            </form>
        </div>
    )
}

export default AddCategory;
