// react/src/component/common/footer.jsx
import React from "react";
import '../../style/footer.css';
import { NavLink } from "react-router-dom";

const Footer = () => {

    return (
        <footer className="footer">
            <div className="footer-links">
                <ul>
                    <NavLink to={"/"}>About Us</NavLink>
                    <NavLink to={"/"}>Contact Us</NavLink>
                    <NavLink to={"/"}>Terms & Cnnditions</NavLink>
                    <NavLink to={"/"}>Privacy Policy</NavLink>
                    <NavLink to={"/"}>FAQs</NavLink>
                </ul>
            </div>
            <div className="footer-info">
                <p>&copy; 2024 Phegon Mart. All right reserved.</p>
            </div>
        </footer>
    )
}
export default Footer;

// frontend/src/app/footer/footer.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css'
})
export class FooterComponent {

}

<footer>
    <div class="footer-links">
        <ul>
            <li><a routerLink="/">About Us</a></li>
            <li><a routerLink="/">Contact Us</a></li>
            <li><a routerLink="/">Terms & Condition</a></li>
            <li><a routerLink="/">Privacy Policy</a></li>
            <li><a routerLink="/">FAQ's</a></li>
        </ul>
    </div>
    <div class="footer-info">
        <p>&copy; 2024 Phegon Mart. All Right Reserved</p>
    </div>
</footer>
